pid: /home/philippeguegan/tmp/thin.pid
address: 127.0.0.1
timeout: 30
wait: 30
port: 4000
log: /home/philippeguegan/www/alouatta/current/log/thin.log
max_conns: 1024
require: []
environment: production
max_persistent_conns: 512
servers: 4
daemonize: true
chdir: /home/philippeguegan/www/alouatta/current